[package]
name = "talk-loco-commands"
version = "0.1.0"
license = "MIT"
keywords = ["talk", "loco"]
description = "KakaoTalk Loco command set"
authors = ["storycraft <storycraft@pancake.sh>"]
edition = "2018"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
bson = "1.1.0"
loco-protocol = "0.1.0"
bson-data-derive = { path = "./bson-data-derive" }