[package]
name = "talk-loco-client"
version = "0.1.0"
license = "MIT"
keywords = ["talk", "loco"]
readme = "readme.md"
description = "Official Loco client with command sets"
repository = "https://github.com/storycraft/talk-loco-client-rs"
authors = ["storycraft <storycraft@pancake.sh>"]
edition = "2018"

[features]
client = ["futures"]
wasm = ["loco-protocol/wasm"]

[dependencies]
serde = { version = "1.0", features = ["derive"] }
futures = { version = "0.3", optional = true }
bson = "1.1.0"
loco-protocol = "2.0.2"

[dev-dependencies]
rsa = "0.5.0"
pem = "0.8"
